language: generic
sudo: required
services:
  - docker

#just for tests
before_install:
  - docker build -t jwan/react-test -f ./client/Dockerfile.dev ./client

# run tests
script:
  - docker run -e CI=true jwan/react-test npm test

# prod builds, no need to specify Dockerfile, it finds it by default
after_success:
  - docker build -t jwan/multi-client ./client
  - docker build -t jwan/multi-nginx ./nginx
  - docker build -t jwan/multi-server ./server
  - docker build -t jwan/multi-worker ./worker
  # push to Dockerhub, login first
  - echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID" --password-stdin
  - docker push jwan/multi-client
  - docker push jwan/multi-nginx
  - docker push jwan/multi-server
  - docker push jwan/multi-worker

